const VALIDATE_FOLLOWUP = "callCenter:VALIDATE_FOLLOWUP"
const REMOVE_FOLLOWUP_ACTION = "callCenter:REMOVE_FOLLOWUP_ACTION"
const GET_FOLLOWUP_BY_ID = "callCenter:GET_FOLLOWUP_BY_ID"
const GET_ALL_FOLLOWUP = "callCenter:GET_ALL_FOLLOWUP"


module.exports = {
    VALIDATE_FOLLOWUP,
    REMOVE_FOLLOWUP_ACTION,
    GET_FOLLOWUP_BY_ID,
    GET_ALL_FOLLOWUP
}