const ADD_SERVICE = "admin:ADD_SERVICE"
const UPDATE_SERVICE = "admin:UPDATE_SERVICE"
const GET_ALL_SERVICES_ADMIN = "admin:GET_ALL_SERVICES_ADMIN"

module.exports = {
    ADD_SERVICE,
    UPDATE_SERVICE,
    GET_ALL_SERVICES_ADMIN
}