const UPDATE_PROFILE = "user:UPDATE_PROFILE"
const UPDATE_PASSWORD = "user:UPDATE_PASSWORD"
const RESET_PASSWORD = "user:RESET_PASSWORD"
const CHANGE_PASSWORD = "user:CHANGE_PASSWORD"
const LOG_OUT = "user:LOG_OUT"

module.exports = {
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    RESET_PASSWORD,
    CHANGE_PASSWORD,
    LOG_OUT
}