const ADD_ORDER = "user:ADD_ORDER"
const GET_ORDER_BY_ID = "user:GET_ORDER_BY_ID"
const GET_ALL_ORDERS = "operator:GET_ALL_ORDERS"
const VALIDATE_ORDER = "operator:VALIDATE_ORDER"
const GET_USER_ORDERS = "user:GET_USER_ORDERS"
const GET_SEEN_ORDERS = "user:GET_SEEN_ORDERS"
const UPDATE_SEEN_ORDERS = "user:UPDATE_SEEN_ORDERS"
const REMOVE_ORDER_ACTION = "operator:REMOVE_ORDER_ACTION"
const UPDATE_ORDER = "user:UPDATE_ORDER"

module.exports = {
    ADD_ORDER,
    GET_ORDER_BY_ID,
    GET_ALL_ORDERS,
    VALIDATE_ORDER,
    GET_USER_ORDERS,
    GET_SEEN_ORDERS,
    UPDATE_SEEN_ORDERS,
    REMOVE_ORDER_ACTION,
    UPDATE_ORDER
}