const UPLOAD_FILE = "user:UPLOAD_FILE"
const UPDATE_FILE = "user:UPDATE_FILE"
const GET_ALL_DOCUMENT = "admin:GET_ALL_DOCUMENT"
const GET_DOCUMENT = "user:GET_DOCUMENT"
const VALIDATE_DOCUMENT = "admin:VALIDATE_DOCUMENT"
const GET_USER_DOCUMENTS = "user:GET_USER_DOCUMENTS"
const GET_SEEN_DOCUMENTS = "user:GET_SEEN_DOCUMENTS"
const UPDATE_SEEN_DOCUMENTS = "user:UPDATE_SEEN_DOCUMENTS"
const REMOVE_DOCUMENT_ACTION = "admin:REMOVE_DOCUMENT_ACTION"
const CHECK_DOCUMENT = "user:CHECK_DOCUMENT"
const EDIT_DOCUMENT = "superAdmin:EDIT_DOCUMENT"

module.exports = {
    UPLOAD_FILE,
    UPDATE_FILE,
    GET_ALL_DOCUMENT,
    GET_DOCUMENT,
    VALIDATE_DOCUMENT,
    GET_USER_DOCUMENTS,
    GET_SEEN_DOCUMENTS,
    UPDATE_SEEN_DOCUMENTS,
    REMOVE_DOCUMENT_ACTION,
    CHECK_DOCUMENT,
    EDIT_DOCUMENT
}